build_from:
  aarch64: "homeassistant/aarch64-base-debian:bullseye"
  amd64: "homeassistant/amd64-base-debian:bullseye"
  armv7: "homeassistant/armv7-base-debian:bullseye"
labels:
  org.opencontainers.image.title: "Scrypted Beta Add-on for Home Assistant"
  org.opencontainers.image.description: "A testing ground for updates to the Scrypted add-on. Install at own risk"
  org.opencontainers.image.source: "https://github.com/aegjoyce/ha-addons"
  org.opencontainers.image.licenses: "Apache"
  org.opencontainers.image.version: "v0.7.40"
