name: Scrypted Beta
version: "v0.7.36"
slug: scrypted-beta
description: A testing ground for updates to the Scrypted add-on. Install at own risk
url: "https://github.com/koush/scrypted"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 0
panel_icon: mdi:memory
hassio_api: true
ingress_stream: true
host_network: true
gpio: true
usb: true
uart: true
image: "ghcr.io/aegjoyce/{arch}-ha-addon-scrypted"
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
map:
  - media:rw
