name: Scrypted Beta
version: "v0.7.97"
slug: scrypted-beta
description: A testing ground for updates to the Scrypted add-on. Install at own risk
url: "https://github.com/koush/scrypted"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 0
panel_icon: mdi:memory
hassio_api: true
ingress_stream: true
host_network: true
gpio: true
usb: true
uart: true
video: true
image: "ghcr.io/aegjoyce/{arch}-ha-addon-scrypted-beta"
environment:
  SCRYPTED_VOLUME: "/data/scrypted_data"
backup_exclude:
  - /server
map:
  - config
  - media:rw
options:
  env_vars: []
schema:
  env_vars:
    - name: match(^SCRYPTED_([A-Z0-9_])+$)
      value: str
devices:
  - /dev/mem
  - /dev/dri/renderD128
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/dri/card0
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
