name: curl test
on:
  workflow_dispatch:
jobs:
  Get-Version:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue using REST API
        run: |
          curl --request GET \
          --url https://api.github.com/users/koush/packages/docker/scrypted/versions \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'accept: application/vnd.github+json' \
          --header 'X-GitHub-Api-Version: 2022-11-28'
